# Based on https://docs.codecov.com/docs

name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Splitwise Go coverage
    steps:
    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Dependencies
      run: go mod download && go mod verify

    - name: Coverage
      run: go test -v -cover -coverprofile=coverage.txt -covermode=atomic .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
